/*
  Auto-generated by Spline
*/

import { useRef, useEffect } from 'react';

import useSpline from '@splinetool/r3f-spline';
import { OrthographicCamera } from '@react-three/drei';
import { useControls } from 'leva';

import useInput from './hooks.js';

export default function Scene({ ...props }) {
    const { nodes, materials } = useSpline(
        'https://prod.spline.design/TMf0OmzEGwiC-IQm/scene.splinecode'
    );
    /*   console.log(nodes);
    console.log(materials);
    console.log({ ...nodes.Cube.material });
    console.log(Object.keys(nodes));
     */ // console.log(structuredClone(nodes.Cube.material));

    const goRef = useRef();
    const key0Ref = useRef();
    const key01Ref = useRef();
    const key02Ref = useRef();
    const keyGroup0Ref = useRef();
    const keyGroup01Ref = useRef();
    const keyGroup02Ref = useRef();
    const keyGroupGoRef = useRef();
    const lPlatRef = useRef();
    const hPlatRef = useRef();
    const keyRefs = [goRef, key0Ref, key01Ref, key02Ref, lPlatRef, hPlatRef];

    const { zero, one, two, go } = useInput();

    function handleKeyPressed(key, ref) {
        if (key) {
            ref.current.position.y = -40;
        } else {
            ref.current.position.y = 15;
        }
    }

    useEffect(() => {
        handleKeyPressed(zero, keyGroup0Ref);
        handleKeyPressed(one, keyGroup01Ref);
        handleKeyPressed(two, keyGroup02Ref);
        handleKeyPressed(go, keyGroupGoRef);
    }, [zero, one, two, go]);

    const { useAmbient } = useControls({
        useAmbient: false,
        wireframe: {
            value: false,
            onChange: (value) => {
                keyRefs.forEach((ref) => {
                    ref.current.material.wireframe = value;
                });
            },
        },
    });

    return (
        <>
            <color attach='background' args={['#e7e5e4']} />
            <group {...props} dispose={null}>
                <group name='platforms' position={[0, -127.52, 0]}>
                    <mesh
                        name='lower platform'
                        geometry={nodes['lower platform'].geometry}
                        material={materials['lower platform Material']}
                        castShadow
                        ref={lPlatRef}
                        receiveShadow
                        position={[0, -38.12, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                    />
                    <mesh
                        name='upper platform'
                        geometry={nodes['upper platform'].geometry}
                        material={materials['upper platform Material']}
                        castShadow
                        receiveShadow
                        ref={hPlatRef}
                        position={[0, -1.34, 0]}
                        rotation={[-Math.PI / 2, 0, 0]}
                    />
                </group>
                <group name='keys' position={[0, 105.58, 0]}>
                    <group
                        name='key Go'
                        ref={keyGroupGoRef}
                        position={[235.65, 0, 229.12]}
                    >
                        <mesh
                            name='Text'
                            geometry={nodes.Text.geometry}
                            material={materials['Text Material']}
                            castShadow
                            receiveShadow
                            position={[-36.17, 145.16, -64.39]}
                            rotation={[-Math.PI / 2, 0, 0]}
                        />
                        <mesh
                            name='Cube'
                            geometry={nodes.Cube.geometry}
                            // material={materials['key orange']}
                            material={nodes.Cube.material}
                            ref={goRef}
                            // material={btnRef.current.material}
                            castShadow
                            receiveShadow
                            position={[0, 76.42, 0]}
                            scale={[1.02, 1, 1]}
                        />
                    </group>
                    <group
                        name='key 2'
                        ref={keyGroup02Ref}
                        position={[235.65, 0, -229.12]}
                    >
                        <mesh
                            name='Text1'
                            geometry={nodes.Text1.geometry}
                            material={materials['Text1 Material']}
                            castShadow
                            receiveShadow
                            position={[-53.64, 145.16, -64.39]}
                            rotation={[-Math.PI / 2, 0, 0]}
                        />
                        <mesh
                            name='Cube1'
                            geometry={nodes.Cube1.geometry}
                            material={materials.key}
                            castShadow
                            ref={key02Ref}
                            receiveShadow
                            position={[0, 76.42, 0]}
                            scale={[1.02, 1, 1]}
                        />
                    </group>
                    <group
                        name='key 0'
                        ref={keyGroup0Ref}
                        position={[-235.65, 0, 229.12]}
                    >
                        <mesh
                            name='Text2'
                            geometry={nodes.Text2.geometry}
                            material={materials['Text2 Material']}
                            castShadow
                            receiveShadow
                            position={[-53.64, 145.16, -64.39]}
                            rotation={[-Math.PI / 2, 0, 0]}
                        />
                        <mesh
                            name='Cube2'
                            geometry={nodes.Cube2.geometry}
                            material={materials.key}
                            castShadow
                            ref={key0Ref}
                            receiveShadow
                            position={[0, 76.42, 0]}
                            scale={[1.02, 1, 1]}
                        />
                    </group>
                    <group
                        name='key 1'
                        ref={keyGroup01Ref}
                        position={[-235.65, 0, -229.12]}
                    >
                        <mesh
                            name='Text3'
                            geometry={nodes.Text3.geometry}
                            material={materials['Text3 Material']}
                            castShadow
                            receiveShadow
                            position={[-53.64, 145.16, -64.39]}
                            rotation={[-Math.PI / 2, 0, 0]}
                        />
                        <mesh
                            name='Cube3'
                            geometry={nodes.Cube3.geometry}
                            material={materials.key}
                            ref={key01Ref}
                            castShadow
                            receiveShadow
                            position={[0, 76.42, 0]}
                            scale={[1.02, 1, 1]}
                        />
                    </group>
                </group>
                <directionalLight
                    name='Directional Light'
                    castShadow
                    intensity={0.7}
                    shadow-mapSize-width={1024}
                    shadow-mapSize-height={1024}
                    shadow-camera-near={-10000}
                    shadow-camera-far={100000}
                    shadow-camera-left={-1000}
                    shadow-camera-right={1000}
                    shadow-camera-top={1000}
                    shadow-camera-bottom={-1000}
                    position={[-507.3, 258.25, 63.99]}
                    rotation={[0, 1.21, 0]}
                    scale={[0.58, 1, 1]}
                />
                <OrthographicCamera
                    name='1'
                    makeDefault={true}
                    zoom={0.3}
                    far={100000}
                    near={-100000}
                    position={[47.87, 883.95, 556.27]}
                    rotation={[-1.57, 0, 0]}
                />

                {/* <ambientLight intensity={0.75} /> */}
                {useAmbient ? (
                    <ambientLight intensity={0.75} />
                ) : (
                    <hemisphereLight
                        name='Default Ambient Light'
                        intensity={0.8}
                        color='#e9e8e8'
                    />
                )}
            </group>
        </>
    );
}
